"""Validates the Phase 05 character references against the acceptance criteria.

Each reference is one isolated fighter painted over a flat #FF00FF void (the generator cannot emit
alpha -- see key-layers.py). Phase 05 does not key them: `asset-manifest.md` specifies
`Processing = none (reference)`, and Phase 09 makes the real alpha sheets. So this script only
measures; it writes nothing.

The references are generated by passing the WHOLE mockup as `--image`, which CLAUDE.md warns
dominates the prompt and invents scenery into the void. That gamble is not argued with here, it is
measured: `void fraction` collapses if the stage survived, and `figure runs` goes to 2 if the
mockup's other fighter came along. This script is what decides whether to spend another generation.

Reads concepts/characters/2026-07-17/<id>.png        (opaque, magenta void)
      concepts/characters/2026-07-17/<id>.prompt.txt (the exact --prompt string)
      concepts/characters/2026-07-17/<id>.job.json   (verbatim `--json` job record)

Run: `npm run check:characters` (or `python scripts/check-characters.py`). Reports every number,
exits non-zero on any failed assertion. Self-tests its own metrics first, every run.
"""

import importlib.util
import json
import sys
from pathlib import Path

import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
CHARACTERS = ROOT / "concepts" / "characters" / "2026-07-17"
MOCKUPS = "concepts/mockups/2026-07-16"

# ponytail: the provenance gate (check_job), the shared-block check and the key-layers thresholds all
# live in art_gate.py now -- Phase 07 was the third caller, which is the trigger this file's own
# comment named. art_gate re-exports key-layers' l1/key/KEY_* so the chain is one hop, not two. Its
# module level is only constants and defs; its main() is __main__-guarded, so importing runs nothing.
_spec = importlib.util.spec_from_file_location("art_gate", ROOT / "scripts" / "art_gate.py")
art_gate = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(art_gate)
l1, key, KEY_RGB, KEY_LO, KEY_HI = (
    art_gate.l1,
    art_gate.key,
    art_gate.KEY_RGB,
    art_gate.KEY_LO,
    art_gate.KEY_HI,
)
check_job, check_blocks, shared_block = art_gate.check_job, art_gate.check_blocks, art_gate.shared_block

# id -> (source mockup basename, which fighter). IDs match the manifest's runtime sprite paths
# (public/sprites/<id>/) so Phase 09 never has to guess a spelling.
FIGHTERS = {
    "brawler": "rooftop-dusk",
    "jiujitsu": "neon-alley",
    "monk": "dojo",
}

# This phase's generation params (nano_banana_pro at 3:4 / 2k, exactly 1 --image reference) are
# art_gate.check_job's defaults, so they are not restated here. Phase 07 overrides them.

# The prompts are one per fighter, but everything from this marker on is shared verbatim. "Consistent
# SNES style" has no honest pixel metric (see the module docstring of the log), so it is enforced by
# construction instead: the three files must carry a byte-identical style block. art_gate.SHARED_MARKER.

VOID_FRAC_MIN = 0.55  # below this the generator kept the stage instead of the character
COL_ART_FRAC = 0.005  # denoise only: a column with less art than this holds no figure
RUN_ART_MIN = 0.10  # a run holding <10% of the biggest run's art is scenery, not a figure
SPECK_ART_MAX = 0.005  # ...and scenery is only tolerated up to 0.5% of the figure's own art
MARGIN_MIN = 0.05  # figure must not touch an edge -- full-body, and crop-safe for sheet extraction
BBOX_H_MIN, BBOX_H_MAX = 0.55, 0.80  # the prompt asks for ~2/3 of frame height


def measure(rgb: np.ndarray, name: str) -> dict:
    """Every acceptance number for one reference. Asserts nothing -- `verdict()` decides."""
    H, W, _ = rgb.shape
    d = l1(rgb, KEY_RGB)

    # key() is the void's own gate: it raises if there is no #FF00FF at all, and asserts the void is
    # flat (sum of per-channel stddevs over d < VOID_PREFILTER <= VOID_SPREAD_MAX). Reused rather
    # than restated so a polluted void fails identically in both scripts.
    #
    # ponytail: that bound catches a BIMODAL void (a blob of off-colour parked in the magenta) but
    # cannot catch a gentle ramp -- a uniform ramp's stddev is range/sqrt(12), and the prefilter only
    # admits pixels within L1 200 of magenta, so the sum tops out near 58 < 60 by construction. A
    # ramp that shallow is still nearly-magenta and keys cleanly, and key-layers.py measured the real
    # void at std 1.6, so the loose bound is doing its job. Upgrade path: bound the L1 range too, if a
    # generator ever paints a wide shallow ramp.
    key(rgb, name)

    void = d < KEY_LO
    art = d >= KEY_HI

    # ponytail: figure count via a 1-D column projection, not connected-component labelling -- two
    # OVERLAPPING figures would read as one. The failure this exists to catch is the mockup's other
    # fighter surviving, and mockups place fighters far apart, so the projection has been enough:
    # 10/10 gens resolved to a single run and no overlap case has occurred. Upgrade path is cheap if
    # one ever does -- scipy.ndimage.label is already importable here (scipy 1.16), it is just not
    # worth the dependency reach until a real asset needs it.
    col_art = art.sum(0)
    cands = _runs(col_art > COL_ART_FRAC * H)
    if not cands:
        return {"size": (W, H), "void_frac": float(void.mean()), "art_frac": float(art.mean()),
                "runs": 0, "run_widths": [], "speck_px": int(art.sum())}

    # Weigh each run by the art it holds, not by its width. A surviving second fighter carries art
    # comparable to the first; an invented speck carries a rounding error. Thresholding columns
    # instead would make the two indistinguishable -- the selftest's speck fixture caught exactly
    # that, when a 4px speck scored as a second figure.
    weights = [int(col_art[a:b].sum()) for a, b in cands]
    biggest = max(weights)
    runs = [r for r, w in zip(cands, weights) if w >= RUN_ART_MIN * biggest]

    x0, x1 = cands[weights.index(biggest)]
    x1 -= 1
    # Rows measured INSIDE the figure's own column band, so a speck elsewhere cannot stretch the bbox.
    rows = np.flatnonzero(art[:, x0 : x1 + 1].sum(1) > COL_ART_FRAC * (x1 - x0 + 1))
    y0, y1 = int(rows[0]), int(rows[-1])

    inside = np.zeros_like(art)
    inside[y0 : y1 + 1, x0 : x1 + 1] = True

    return {
        "size": (W, H),
        "void_frac": float(void.mean()),
        "art_frac": float(art.mean()),
        "runs": len(runs),
        "run_widths": [b - a for a, b in runs],
        "bbox": (x0, y0, x1, y1),
        "bbox_w": (x1 - x0 + 1) / W,
        "bbox_h": (y1 - y0 + 1) / H,
        "margins": {
            "left": x0 / W,
            "right": (W - 1 - x1) / W,
            "top": y0 / H,
            "bottom": (H - 1 - y1) / H,
        },
        # Art outside the figure's bbox: scenery the generator invented into the void.
        "speck_px": int((art & ~inside).sum()),
        "main_art_px": biggest,
    }


def _runs(flags: np.ndarray) -> list[tuple[int, int]]:
    """Half-open [start, end) runs of True in a 1-D bool array."""
    idx = np.flatnonzero(np.diff(np.concatenate(([0], flags.astype(np.int8), [0]))))
    return [(int(a), int(b)) for a, b in zip(idx[::2], idx[1::2])]


def verdict(m: dict, name: str) -> list[str]:
    """Acceptance failures for one reference, as human sentences. Empty list == PASS."""
    bad = []
    if m["runs"] != 1:
        bad.append(
            f"{m['runs']} figures, expected exactly 1 (run widths {m['run_widths']}) -- the "
            "mockup's other fighter, or invented scenery, survived into the void"
        )
    if m["void_frac"] < VOID_FRAC_MIN:
        bad.append(
            f"void is {m['void_frac']:.1%} of canvas, need >={VOID_FRAC_MIN:.0%} -- the generator "
            "kept the stage instead of isolating the character"
        )
    # `runs` alone does NOT honestly enforce "exactly one figure": RUN_ART_MIN drops a run holding
    # <10% of the main figure's art, so a small opponent or a background silhouette slips through it.
    # (Review caught this with a 50x25 second figure: runs=1, and specks were merely reported.) The
    # two gates are complements -- anything big enough to be a figure trips `runs`, anything smaller
    # but larger than noise trips this. Together they cover everything outside the figure's bbox.
    if m["runs"] == 1 and m["speck_px"] > SPECK_ART_MAX * m["main_art_px"]:
        bad.append(
            f"{m['speck_px']}px of art outside the figure ({m['speck_px'] / m['main_art_px']:.1%} of "
            f"the figure's own art, max {SPECK_ART_MAX:.1%}) -- a second figure or invented scenery "
            "is sitting in the void"
        )
    if m["runs"] == 1:
        for side, v in m["margins"].items():
            if v < MARGIN_MIN:
                bad.append(
                    f"{side} margin {v:.1%} < {MARGIN_MIN:.0%} -- figure touches the edge, not "
                    "full-body / not crop-safe"
                )
        if not BBOX_H_MIN <= m["bbox_h"] <= BBOX_H_MAX:
            bad.append(
                f"figure is {m['bbox_h']:.1%} of frame height, want "
                f"{BBOX_H_MIN:.0%}-{BBOX_H_MAX:.0%}"
            )
    return bad


def selftest() -> None:
    """Synthetic fixtures for the pixel metrics, run before the oracle is trusted on real art.

    Phase 04 shipped two *wrong* metrics and recorded that a wrong metric is more dangerous than no
    metric. This one decides whether to spend more credits, so it proves itself first. In-memory, no
    fixture files, cheap enough to always run.

    Scope, stated honestly: this covers `measure()`/`verdict()` -- void, figure count, speck area,
    bbox height, and the bottom/left margins that the fixtures happen to violate. It does NOT
    independently exercise every margin direction, the upper bbox bound, the shared-block identity
    check, or `check_job()`. Those are covered by the real run in `main()`, not by fixtures.
    """

    def canvas(h=400, w=300):
        return np.full((h, w, 3), KEY_RGB, dtype=np.uint8)

    def figure(img, x0, y0, x1, y1, colour=(20, 200, 40)):
        img[y0:y1, x0:x1] = colour
        return img

    ok = figure(canvas(), 110, 60, 190, 330)  # ~68% tall, centred, one figure
    assert verdict(measure(ok, "ok"), "ok") == [], "a valid reference must pass"

    two = figure(figure(canvas(), 40, 60, 110, 330), 190, 60, 260, 330)
    assert any("2 figures" in b for b in verdict(measure(two, "two"), "two")), (
        "two separated figures must fail the run count"
    )

    cropped = figure(canvas(), 110, 60, 190, 400)  # runs off the bottom edge
    assert any("bottom margin" in b for b in verdict(measure(cropped, "cropped"), "cropped")), (
        "a figure touching an edge must fail the margin check"
    )

    stage = figure(canvas(), 0, 0, 300, 340)  # the mockup's stage survived
    assert any("void is" in b for b in verdict(measure(stage, "stage"), "stage")), (
        "a surviving stage must fail the void fraction"
    )

    short = figure(canvas(), 130, 180, 170, 300)  # only 30% tall
    assert any("frame height" in b for b in verdict(measure(short, "short"), "short")), (
        "a too-small figure must fail the bbox height"
    )

    speck = figure(figure(canvas(), 110, 60, 190, 330), 280, 20, 284, 24)
    m = measure(speck, "speck")
    assert verdict(m, "speck") == [] and m["speck_px"] > 0, "a speck is reported, not fatal"

    # The gap the two-figure fixture above cannot reach: a second figure small enough to slip under
    # RUN_ART_MIN. Found by review, not by this suite -- which is why it is pinned here now.
    small = figure(figure(canvas(), 110, 60, 190, 330), 250, 100, 300, 125)
    m = measure(small, "small")
    assert m["runs"] == 1, "precondition: the small opponent must slip under the run filter"
    assert any("outside the figure" in b for b in verdict(m, "small")), (
        "a second figure too small to trip the run filter must still fail on speck area"
    )

    # Bimodal, not a ramp: see the ceiling named in measure() -- a gentle ramp cannot exceed the
    # inherited VOID_SPREAD_MAX, so testing one would assert a behaviour the metric does not have.
    twotone = canvas()
    twotone[:, 150:, 1] = 190  # half the void parked well off pure magenta, still inside prefilter
    figure(twotone, 110, 60, 190, 330)
    try:
        measure(twotone, "twotone")
    except AssertionError:
        pass
    else:
        raise AssertionError("a two-tone void must fail key()'s flatness assert")

    novoid = np.full((400, 300, 3), (20, 200, 40), dtype=np.uint8)
    try:
        measure(novoid, "novoid")
    except AssertionError:
        pass
    else:
        raise AssertionError("no void at all must fail key()")

    print(
        "selftest: 9 fixtures OK (valid, two-figure, small-opponent, cropped, stage, short, speck, "
        "two-tone, no-void)"
    )


def main() -> int:
    selftest()

    prompts = {}
    for fid in FIGHTERS:
        p = CHARACTERS / f"{fid}.prompt.txt"
        if not p.exists():
            print(f"FAIL {fid}: {p} is missing")
            return 1
        prompts[fid] = p.read_text(encoding="utf-8")

    failures = []

    bad_blocks = check_blocks(prompts)
    failures += bad_blocks
    if not bad_blocks:
        print(f"shared style block: identical across {len(prompts)} prompts "
              f"({len(shared_block(prompts))} chars)")

    for fid, mockup in FIGHTERS.items():
        png = CHARACTERS / f"{fid}.png"
        if not png.exists():
            failures.append(f"{fid}: {png.name} is missing")
            continue

        rgb = np.array(Image.open(png).convert("RGB"))
        try:
            m = measure(rgb, fid)
        except AssertionError as e:
            failures.append(f"{fid}: {e}")
            continue

        bad = verdict(m, fid) + check_job(fid, prompts[fid], CHARACTERS)
        mark = "PASS" if not bad else "FAIL"
        print(
            f"\n{mark} {fid}  <- {MOCKUPS}/{mockup}.png\n"
            f"  size        {m['size'][0]}x{m['size'][1]}  ({m['size'][0] / m['size'][1]:.4f}:1)\n"
            f"  void        {m['void_frac']:.1%} of canvas   art {m['art_frac']:.1%}\n"
            f"  figures     {m['runs']}  (column runs, widths {m['run_widths']})\n"
            f"  bbox        {m['bbox']}  {m['bbox_w']:.1%} w x {m['bbox_h']:.1%} h\n"
            f"  margins     L {m['margins']['left']:.1%}  R {m['margins']['right']:.1%}  "
            f"T {m['margins']['top']:.1%}  B {m['margins']['bottom']:.1%}\n"
            f"  specks      {m['speck_px']} px outside the figure bbox"
        )
        for b in bad:
            print(f"  !! {b}")
        failures += [f"{fid}: {b}" for b in bad]

    print()
    if failures:
        print(f"FAILED ({len(failures)}):")
        for f in failures:
            print(f"  - {f}")
        return 1
    print(f"all {len(FIGHTERS)} character references pass")
    return 0


if __name__ == "__main__":
    sys.exit(main())
